mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config.logic-delete-value: 1 # # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 0 # 逻辑未删除值（默认 0）
